version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - ruby --version

  post_build:
    commands:
      - pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_ruby2_7.py -n 4
