version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.x

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - go version

  post_build:
    commands:
      - pytest -vvv --capture=tee-sys tests/integration/build_invoke/test_build_invoke_go1_x.py -n 4
      - pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_go1_x.py -n 4
