version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - gradle --version
      - mvn --version

  post_build:
    commands:
      - python3 -m pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_java8.py -n 4
