version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python3 --version

  post_build:
    commands:
      - pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_python3_8.py -n 4
