version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - gradle --version
      - mvn --version

  post_build:
    commands:
      - pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_java11.py -n 4
