version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - node --version

  post_build:
    commands:
      - pytest -vvv --capture=tee-sys tests/integration/unit_test/test_unit_test_nodejs12_x.py -n 4
